=== koriym/homebrew-malt/docs/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "project_name": {
            "type": "string"
        },
        "public_dir": {
            "type": "string"
        },
        "dependencies": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "ports": {
            "type": "object",
            "properties": {
                "php": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "redis": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "memcached": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "nginx": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "httpd": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "mysql": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            },
            "additionalProperties": false
        },
        "php_extensions": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": [
        "project_name",
        "public_dir",
        "dependencies",
        "ports",
        "php_extensions"
    ],
    "additionalProperties": false
}

=== koriym/homebrew-malt/malt.json
{
  "project_name": "myapp",
  "public_dir": "public",
  "dependencies": [
    "php@8.4",
    "mysql@8.0",
    "composer",
    "httpd",
    "nginx",
    "redis",
    "memcached"
  ],
  "ports": {
    "php": [9000],
    "memcached": [11211],
    "nginx": [80, 443],
    "httpd": [8080, 8443],
    "mysql": [3306],
    "redis": [6379]
  },
  "php_extensions": [
    "xdebug",
    "redis",
    "apcu"
  ]
}

=== koriym/homebrew-malt/share/malt/default.json
{
  "project_name": "myapp",
  "public_dir": "public",
  "dependencies": [
    "php@8.4",
    "composer",
    "redis",
    "nginx",
    "httpd",
    "mysql@8.0"
  ],
  "ports": {
    "php": [9000],
    "redis": [6379],
    "memcached": [11211],
    "nginx": [80, 443],
    "httpd": [8080, 8443],
    "mysql": [3306]
  },
  "php_extensions": [
    "xdebug",
    "redis",
    "apcu"
  ]
}

=== koriym/homebrew-malt/share/default.json
{
  "project_name": "myapp",
  "public_dir": "public",
  "dependencies": [
    "php@8.4",
    "mysql@8.0",
    "httpd",
    "nginx",
    "redis",
    "memcached",
    "composer"
  ],
  "ports": {
    "php": [9000],
    "mysql": [3306],
    "httpd": [8080],
    "nginx": [80],
    "redis": [6379],
    "memcached": [11211]
  },
  "php_extensions": [
    "xdebug",
    "pcov",
    "redis",
    "memcached",
    "apcu"
  ]
}
